source "https://rubygems.org"
ruby "2.4.0"
gem 'sinatra'
gem 'puma'
gem 'httparty'
gem 'dotenv'
gem 'resque'
gem 'activerecord'
gem 'rake'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'activesupport'
gem 'resque'