development:
    adapter:  mysql2
    encoding: utf8
    database: submetrics
    pool: 5
    username: huc5zdtbvxhz596e
    password: cjufyxjnjmg86n4l
    host: erxv1bzckceve5lh.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
    
    port: 3306
    secure_auth: false


production: 
    adapter:  mysql2
    encoding: utf8
    database: submetrics
    pool: 5
    username: huc5zdtbvxhz596e
    password: cjufyxjnjmg86n4l>
    host: erxv1bzckceve5lh.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
    
    port: 3306





#connect user, pass, host, port, database, socket, flags