default: &default
    adapter: mysql2
    encoding: utf8
    database: submetrics
    pool: 5
    username: <%= ENV['MYSQL_USER'] %>
    password: <%= ENV['MYSQL_PASS'] %>
    #username: "floyd"
    #password: "10tul10"
    #host: localhost
    host: <%= ENV['MYSQL_HOST'] %>
    port: 3306
    secure_auth: false


development:
  <<: *default
  database: submetrics




#connect user, pass, host, port, database, socket, flags